### ISSUE TITLE
Plan out API Calls

### ISSUE THREAD

**Issue by brsm3129** [brsm3129/Recitation-15-Team-8-Weatherdle#14]
As a software developer, I want to plan out the API calls for my application, so that I can efficiently retrieve data from external APIs and integrate it into my application.

**Comment by adamadl** [comment]
Acceptance Criteria: The API calls should be planned out based on the weather data needed for the application. The API calls should be well-documented, including the endpoint URLs, request parameters, and response formats. The API calls should be tested for functionality and reliability, including error handling and response time.
