### ISSUE TITLE
Previous Guesses Tables

### ISSUE THREAD

**Issue by brsm3129** [brsm3129/Recitation-15-Team-8-Weatherdle#18]
As a user, upon entering guesses for the game, on subsequent guesses, I should be able to see a table containing all of my previous guesses along with the information related to those guesses.

**Comment by adamadl** [comment]
Acceptance Criteria: As a user, when entering a subsequent guess, I should see the information of my previous guess such as the city name, the summer high, summer low, longest day, winter high, winter low, and length of shortest day.
